/* BEACON */
DROP TABLE BEACON 
	CASCADE CONSTRAINTS;

/* BOARD */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* REPLY */
DROP TABLE REPLY 
	CASCADE CONSTRAINTS;

/* USERS */
DROP TABLE USERS 
	CASCADE CONSTRAINTS;

/* BEACON */
CREATE TABLE BEACON (
	B_IDX NUMBER(11) NOT NULL, /* B_IDX */
	B_ID VARCHAR2(100) NOT NULL, /* B_ID */
	B_SPOTNAME VARCHAR2(100), /* B_SPOTNAME */
	B_LOCACTION VARCHAR2(100), /* B_LOCACTION */
	B_PAGE VARCHAR2(100) /* B_PAGE */
);

ALTER TABLE BEACON
	ADD
		CONSTRAINT PK_BEACON
		PRIMARY KEY (
			B_IDX
		);

/* BOARD */
CREATE TABLE BOARD (
	DOC_NUM NUMBER(30) NOT NULL, /* DOC_NUM */
	USERID VARCHAR2(100), /* USERID */
	LAT NUMBER, /* LAT */
	LON NUMBER, /* LON */
	PIC_FILE VARCHAR2(300), /* PIC_FILE */
	MOV_FILE VARCHAR2(300), /* MOV_FILE */
	DOC_TLE VARCHAR2(100), /* DOC_TLE */
	DOC_CON VARCHAR2(500), /* DOC_CON */
	DOC_DATE DATE, /* DOC_DATE */
	DOC_HIT NUMBER, /* DOC_HIT */
	DOC_TF VARCHAR2(100), /* DOC_TF */
	DOC_TAG VARCHAR2(100), /* DOC_TAG */
	PLACE VARCHAR2(100), /* PLACE */
	ALERT_DATE DATE /* ALERT_DATE */
);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			DOC_NUM
		);

/* REPLY */
CREATE TABLE REPLY (
	RE_NUM VARCHAR2(30), /* RE_NUM */
	RE_CON VARCHAR2(100), /* RE_CON */
	DOC_NUM NUMBER(30), /* DOC_NUM */
	USER_ID VARCHAR2(40), /* USER_ID */
	NICKNAME VARCHAR2(30), /* NICKNAME */
	RE_DATE DATE /* RE_DATE */
);

/* USERS */
CREATE TABLE USERS (
	USERID VARCHAR2(100) NOT NULL, /* USERID */
	NICKNAME VARCHAR2(100), /* NICKNAME */
	USERIMG VARCHAR2(100), /* USERIMG */
	GRADE VARCHAR2(100) /* GRADE */
);

ALTER TABLE USERS
	ADD
		CONSTRAINT SYS_C007516
		PRIMARY KEY (
			USERID
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_USERS_TO_BOARD
		FOREIGN KEY (
			USERID
		)
		REFERENCES USERS (
			USERID
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_BOARD_TO_REPLY
		FOREIGN KEY (
			DOC_NUM
		)
		REFERENCES BOARD (
			DOC_NUM
		);